// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-pe3s2lnP7nHxAIp6MsCzo_eSFfxYGtw',
    appId: '1:620245110276:web:1bb71a30dd16adb22f2f51',
    messagingSenderId: '620245110276',
    projectId: 'appartement-df9a3',
    authDomain: 'appartement-df9a3.firebaseapp.com',
    storageBucket: 'appartement-df9a3.appspot.com',
    measurementId: 'G-JMHD6RJPRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-92fJ33igfZ5ps10E6MBWVMMCRYStLE',
    appId: '1:620245110276:android:e227ce4993b12c1e2f2f51',
    messagingSenderId: '620245110276',
    projectId: 'appartement-df9a3',
    storageBucket: 'appartement-df9a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYfHSj-BUrDwnskFEI8eM39MJKODU6ec',
    appId: '1:620245110276:ios:89223b524419749f2f2f51',
    messagingSenderId: '620245110276',
    projectId: 'appartement-df9a3',
    storageBucket: 'appartement-df9a3.appspot.com',
    iosClientId: '620245110276-m6rn45n17hluvnm1a812hhrev6bhmdgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appartement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJYfHSj-BUrDwnskFEI8eM39MJKODU6ec',
    appId: '1:620245110276:ios:89223b524419749f2f2f51',
    messagingSenderId: '620245110276',
    projectId: 'appartement-df9a3',
    storageBucket: 'appartement-df9a3.appspot.com',
    iosClientId: '620245110276-m6rn45n17hluvnm1a812hhrev6bhmdgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appartement',
  );
}
